version: '3'

services:
  webfrontend:
    image: webfrontend:latest      
    ports: 
      - "5081:80"
    networks:
      - frontend
    depends_on: 
      - mywebapi
    deploy:
      replicas: 1
      
  mywebapi:
    image: mywebapi:latest       
    ports: 
      - "5011:80"
    networks:
      - frontend
    depends_on: 
      - sqlserver
      
  sqlserver:  
    image: mcr.microsoft.com/mssql/server:latest  
    environment:  
      ACCEPT_EULA: "Y"  
      SA_PASSWORD: "BigPassw0rd"      
    ports: 
      - "1433:1433"  
    networks:
      - frontend
    deploy:
      replicas: 1
networks:
  frontend: